### ISSUE TITLE
Support for multi-time frame data

### ISSUE THREAD

**Issue by lleewwiiss** [kieran-mackle/AutoTrader#4]
**Is your feature request related to a problem? Please describe.**
Support for allowing to read in 2+ different time frames at a time, this helps if you are building a strategy around higher time frame indicators but want to trade on a lower time frame.

**Describe the solution you'd like**
Similar to watchlist which allows for a list of product codes, allow for a list of time frames.

**Describe alternatives you've considered**
I realise you can just get the data manually and load it manually in the `init` of your strategy, but loading the data in your runfile will overwrite the data you specified in the YAML, so allowing for additional time frames, or another variable for supplementary data would be ideal.

**Additional context**
n/a

**Comment by kieran-mackle** [comment]
Closing this issue now. For future reference, the [strategy configuration docs](https://kieran-mackle.github.io/AutoTrader/docs/configuration-strategy#overview-of-options) covers how to include multiple timeframes.

**Comment by ziyedbe** [comment]
I have the following error when I try to run any strategy using multi time frame data, even for MTF_ema_crossover
`AutoTraderBot assigned to trade BTC-USD with virtual broker using EMA Crossover.

Trading...

  0%|                                                                                               | 0/2678400 [00:00<?, ?it/s]Traceback (most recent call last):
  File "PATH/Desktop\work\shared\personal\autotrader-demo\runfile.py", line 9, in <module>
    at.run()
  File "PATH/AppData\Local\Programs\Python\Python39\lib\site-packages\autotrader\autotrader.py", line 1142, in run  
    self._main()
  File "PATH/AppData\Local\Programs\Python\Python39\lib\site-packages\autotrader\autotrader.py", line 1660, in _main    self._trade_update_loop()
  File "PATH/AppData\Local\Programs\Python\Python39\lib\site-packages\autotrader\autotrader.py", line 2134, in _trade_update_loop
    bot._update(timestamp=timestamp)
  File "PATH/AppData\Local\Programs\Python\Python39\lib\site-packages\autotrader\autobot.py", line 306, in _update  
    self._update_virtual_broker(current_bars)
  File "PATH/AppData\Local\Programs\Python\Python39\lib\site-packages\autotrader\autobot.py", line 663, in _update_virtual_broker
    brokers = self._instrument_to_broker[product]
KeyError: '1h'
 13%|██████████                                                                 | 360000.0/2678400 [00:00<00:01, 2014412.79it/s] `
