### ISSUE TITLE
Plot Error when running backtest on multiple pairs

### ISSUE THREAD

**Issue by ziyedbe** [kieran-mackle/AutoTrader#75]
**Describe the bug**
When I run the backtest on multiple pairs, i get the following error
```
Traceback (most recent call last):
  File "PATH\Desktop\work\shared\personal\autotrader-demo\runfile.py", line 15, in <module>
    broker = at.run()
             ^^^^^^^^
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 1142, in run
    self._main()
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 1660, in _main
    self._trade_update_loop()
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 2310, in _trade_update_loop
    self.shutdown()
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 2069, in shutdown
    self.plot_backtest()
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 1498, in plot_backtest
    portfolio_plot()
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autotrader.py", line 1483, in portfolio_plot
    ap._portfolio_plot(self.trade_results)
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autoplot.py", line 707, in _portfolio_plot
    self._add_to_autoscale_args(levsource, levfig.y_range)
  File "PATH\AppData\Local\Programs\Python\Python311\Lib\site-packages\autotrader\autoplot.py", line 514, in _add_to_autoscale_args
    if source.data["plot_data"].max() == source.data["plot_data"].min():
       ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'plot_data'
```

**To Reproduce**
runfile.py
```python
at = AutoTrader()
at.configure(verbosity=1, show_plot=True, feed='yahoo')#,broker="dydx")
at.add_strategy('ema_crossover')
at.backtest(start='1/1/2022', end='1/10/2022')
at.virtual_account_config(initial_balance=1000, leverage=5,spread=0.00005)
at.run()
```

ema_crossover.yaml
```yaml
NAME: 'EMA Crossover'
MODULE: 'ema_crossover'
CLASS: 'EMAcrossOver'
INTERVAL: '1h'
PERIOD: '24h'
RISK_PC: 2
SIZING: 'risk'
PARAMETERS:
  slow_ema: 50
  fast_ema: 21
  RR: 3.0

# Define pairs to monitor
WATCHLIST: ['BTC-USD','ETH-USD','BNB-USD']
```

**Expected behavior**
Create 3 graphs one for each pair in the watchlist

**Version of AutoTrader being used**
0.12.0

**Comment by harsh-phoenix** [comment]
![image](https://user-images.githubusercontent.com/57630835/218652070-26cecde2-be2f-4312-8a4b-ead80d417934.png)

even i am facing this issue while plotting MACD,  i am unable to resolve error
