### ISSUE TITLE
help with issue

### ISSUE THREAD

**Issue by milandijhon** [kieran-mackle/AutoTrader#80]
cant seem to solve this, please help:  Traceback (most recent call last):
  File "C:\GitHub_Projects\Autotrader\AutoTrader\testrun.py", line 6, in <module>
    at.run()
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autotrader.py", line 1142, in run
    self._main()
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autotrader.py", line 1613, in _main
    bot = AutoTraderBot(
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autobot.py", line 223, in __init__
    self._refresh_data(deploy_dt)
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autobot.py", line 449, in _refresh_data
    data, multi_data, quote_data, auxdata = self.Stream.refresh(timestamp=timestamp)
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\utilities.py", line 1174, in refresh
    data = data_func(
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autodata.py", line 377, in _oanda
    data = self._response_to_df(response)
  File "C:\GitHub_Projects\Autotrader\AutoTrader\autotrader\autodata.py", line 608, in _response_to_df      
    raise Exception(
Exception: Error dowloading data - please check instrument format and try again

**Comment by pboachie** [comment]
Wrong instrument is being used @milandijhon. For example Yahoo uses "EURUSD=X" where oanda uses "EUR_USD". They all mean the same. With Oanda, you need to replace the / with _

yfinance Example
![image](https://github.com/kieran-mackle/AutoTrader/assets/9089767/41a795e7-de8d-490a-becd-163e1eff7974)


Oanda Example
![image](https://github.com/kieran-mackle/AutoTrader/assets/9089767/f7171b9f-263e-42c5-88f8-97b7862d7103)
